### ISSUE TITLE
わかりづらい

### ISSUE THREAD

**Issue by c0a21136** [C0A21130/ProjExD#11]
https://github.com/C0A21130/ProjExD/blob/e7b5cab5828c4defee0a702ec71794ed8dcfdcfe/ex03/maze.py#L22
何をしてるのかわかりづらいよ

**Comment by C0A21130** [comment]
> https://github.com/C0A21130/ProjExD/blob/e7b5cab5828c4defee0a702ec71794ed8dcfdcfe/ex03/maze.py#L22
> 
> 
> 何をしてるのかわかりづらいよ

コメントを追加したので確認お願いします。
