### ISSUE TITLE
コメント追加のお願い

### ISSUE THREAD

**Issue by C0A21138** [C0A21130/ProjExD#12]
https://github.com/C0A21130/ProjExD/blob/e7b5cab5828c4defee0a702ec71794ed8dcfdcfe/ex03/maze.py#L23

この箇所での処理内容について、コメント追加をお願いします。

**Comment by C0A21130** [comment]
> https://github.com/C0A21130/ProjExD/blob/e7b5cab5828c4defee0a702ec71794ed8dcfdcfe/ex03/maze.py#L23
> 
> この箇所での処理内容について、コメント追加をお願いします。

コメントを追加しました。
