### ISSUE TITLE
バグ修正案

### ISSUE THREAD

**Issue by c0a21024b3** [C0A21130/ProjExD#13]
この行の後に、31行目と同じでbom_rct = bom_sfc.get_rect() を入れると爆弾が正しく表示されると思います
https://github.com/C0A21130/ProjExD/blob/272c969b3a7edd7c404056b9285d34f04c7a133b/ex04/dodge_bomb.py#L71

**Comment by C0A21130** [comment]
> この行の後に、31行目と同じでbom_rct = bom_sfc.get_rect() を入れると爆弾が正しく表示されると思います
> 
> https://github.com/C0A21130/ProjExD/blob/272c969b3a7edd7c404056b9285d34f04c7a133b/ex04/dodge_bomb.py#L71

赤い丸が発生することができました。今後は黒い四角をなくせるように修正します。
