### ISSUE TITLE
このprintはいらない

### ISSUE THREAD

**Issue by c0a21136** [C0A21130/ProjExD#14]
https://github.com/C0A21130/ProjExD/blob/272c969b3a7edd7c404056b9285d34f04c7a133b/ex04/dodge_bomb.py#L64
このprintは何のためにあるのでしょうか？

**Comment by C0A21130** [comment]
> https://github.com/C0A21130/ProjExD/blob/272c969b3a7edd7c404056b9285d34f04c7a133b/ex04/dodge_bomb.py#L64
> 
> 
> このprintは何のためにあるのでしょうか？

必要がなかったので削除しました
