### ISSUE TITLE
不要なモジュール

### ISSUE THREAD

**Issue by c0a21024b3** [C0A21130/ProjExD#16]
不要なモジュールがインポートされているので削除お願いします
https://github.com/C0A21130/ProjExD/blob/ddda72a60df3fbe5918d0a2eee9b3a8438fd763b/ex05/fight_kokaton.py#L1

**Comment by C0A21130** [comment]
> 不要なモジュールがインポートされているので削除お願いします
> 
> https://github.com/C0A21130/ProjExD/blob/ddda72a60df3fbe5918d0a2eee9b3a8438fd763b/ex05/fight_kokaton.py#L1

不要なモジュールを削除しました
