### ISSUE TITLE
アルファベットが被ると思います

### ISSUE THREAD

**Issue by c0a21024b3** [C0A21130/ProjExD#2]
これだと同じアルファベットを対象文字に指定する可能性があると思います。
https://github.com/C0A21130/ProjExD/blob/45426e1fc5c2df0b9c47df3c4b8477668935f25e/ex01/alphabet.py#L9

**Comment by C0A21130** [comment]
> これだと同じアルファベットを対象文字に指定する可能性があると思います。
> 
> https://github.com/C0A21130/ProjExD/blob/45426e1fc5c2df0b9c47df3c4b8477668935f25e/ex01/alphabet.py#L9

その後にnot in で判別しているので確認お願いします
