### ISSUE TITLE
インラインコメントの空白

### ISSUE THREAD

**Issue by Inazuma110** [C0A21130/ProjExD#24]
https://github.com/C0A21130/ProjExD/blob/a3e8587b1d06b328e901f616c34599e7aa9e99ea/ex06/teamgame.py#L9

プログラム同じ行のコメントはインラインコメントと呼びます．
このインラインコメントの利用は控えめに，使う場合はプログラムと2つ以上のスペースを開けると良いそうです．
全部直すのは大変だと思いますが，今後気をつけると良いかもしれません．

参考 https://pep8-ja.readthedocs.io/ja/latest/#section-18

**Comment by C0A21130** [comment]
ありがとうございます。今後コメントをつける際には注意します。
他のメンバーが修正したのでよろしくお願いします。
