### ISSUE TITLE
ボタンの処理が見づらい

### ISSUE THREAD

**Issue by c0a21024b3** [C0A21130/ProjExD#5]
ボタンの処理を一つにまとめるのではなく、数字、イコール、累乗などで関数を分けた方が見やすいと思った
https://github.com/C0A21130/ProjExD/blob/c3d7dcb90ed8d0dbc47a4b84dce127cc7ff33718/ex02/calc.py#L11

**Comment by C0A21130** [comment]
関数に分けることで見やすくなりました。

**Comment by C0A21130** [comment]
> ボタンの処理を一つにまとめるのではなく、数字、イコール、累乗などで関数を分けた方が見やすいと思った
> 
> https://github.com/C0A21130/ProjExD/blob/c3d7dcb90ed8d0dbc47a4b84dce127cc7ff33718/ex02/calc.py#L11

関数に分けることで見やすくなりました。
