### ISSUE TITLE
コメントの追加お願いします。

### ISSUE THREAD

**Issue by C0A21138** [C0A21130/ProjExD#7]
https://github.com/C0A21130/ProjExD/blob/885dc6a37a878d3588c8c3f67cac7535438845c3/ex02/calc.py#L9

何をしているのか、コメントで説明があると、伝わりやすいプログラムになると感じました。

**Comment by C0A21130** [comment]
追加しました。

**Comment by C0A21130** [comment]
> https://github.com/C0A21130/ProjExD/blob/885dc6a37a878d3588c8c3f67cac7535438845c3/ex02/calc.py#L9
> 
> 何をしているのか、コメントで説明があると、伝わりやすいプログラムになると感じました。
追加しました。
