### ISSUE TITLE
バグ修正案

### ISSUE THREAD

**Issue by c0a21024b3** [C0A21130/ProjExD#9]
ゴールした瞬間にmaze_lstの数字を2から0にすればメッセージボックスの量産を防げると思います
https://github.com/C0A21130/ProjExD/blob/002ab4933a0b243b04ecd786efae7e48dc4e1af8/ex03/maze.py#L64

**Comment by C0A21130** [comment]
> ゴールした瞬間にmaze_lstの数字を2から0にすればメッセージボックスの量産を防げると思います
> 
> https://github.com/C0A21130/ProjExD/blob/002ab4933a0b243b04ecd786efae7e48dc4e1af8/ex03/maze.py#L64

修正が終わりました。
